version: '3'

services:

  oxid6_apache:
    build: container/apache_php7/.
    hostname: ${HOSTNAME}
    container_name: apache.${HOSTNAME}
    depends_on:
      - oxid6_mysql
    volumes:
      - ${PWD}/../:/var/www/html/:cached
      - "~/.composer:/var/www/.composer"
      - "./container/apache_php7/files/php.ini:/usr/local/etc/php/php.ini"
    environment:
      APACHE_PORT: ${APACHE_PORT}
      OXID_VERSION: ${OXID_VERSION}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${APACHE_PORT}:80
    links:
      - oxid6_mailhog:mail.server

  oxid6_mysql:
    image: mysql:5.7
    container_name: mysql.${HOSTNAME}
    hostname: mysql.${HOSTNAME}
    volumes:
      - ${PWD}/data/mysql/:/var/lib/mysql
      - ./container/mysql/my.cnf:/etc/mysql/conf.d/z_my.cnf
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  oxid6_mailhog:
    hostname: mailhog.${HOSTNAME}
    container_name: mailhog.${HOSTNAME}
    image: mailhog/mailhog:latest
    ports:
      - ${MAILHOG_PORT}:8025

  oxid6_phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin.${HOSTNAME}
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: mysql.${HOSTNAME}
