version: '3'

services:

  oxid6_apache:
    build: container/apache_php7/.
    hostname: ${DOMAIN}
    container_name: ${CONTAINER_NAME}
    depends_on:
      - oxid6_mysql
    volumes:
      - ${PWD}/../:/var/www/html/:cached
    environment:
      DOMAIN: ${DOMAIN}
      OXID_VERSION: ${OXID_VERSION}
      OXID_DEMODATA: ${OXID_DEMODATA}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      COMPOSER_CACHE_DIR: /var/www/.composer
    ports:
      - ${APACHE_PORT}:80
    links:
      - oxid6_mailhog:mail.server

  oxid6_mysql:
    image: mysql:5.7
    hostname: mysql.${DOMAIN}
    volumes:
      - ${PWD}/data/mysql/:/var/lib/mysql
      - ./container/mysql/my.cnf:/etc/mysql/conf.d/z_my.cnf
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  oxid6_mailhog:
    hostname: mailhog.${DOMAIN}
    image: mailhog/mailhog:latest
    ports:
      - ${MAILHOG_PORT}:8025

  oxid6_phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: oxid6_mysql
